### ISSUE TITLE
Routes for Courses broken?

### ISSUE THREAD

**Issue by Rahbaran** [meteorcrowd/crowducate-next#1]
Not sure if you're aware (as you're restructuring). Anyway, I get this:
![screenshot 2015-02-05 16 55 02](https://cloud.githubusercontent.com/assets/3035315/6063470/d432f888-ad57-11e4-9814-3353db4a2106.png)

**Comment by brylie** [comment]
Thanks for the feedback. I have wired up the route in a subsequent commit. We are prototyping fast and breaking things often, so the functionality is not fully fleshed out.

**Comment by Rahbaran** [comment]
ah ok, thought so! :)

**Comment by brylie** [comment]
I just pushed the most recent work, which includes the course page route.

The course page is coming together as I merge templates from Illya's (@nizyev) static mockups. You can see Illya's static mockups by visiting `localhost:3000/singleresourcepage`

**Comment by Rahbaran** [comment]
fabulous progress. very impressed.

**Comment by 55** [comment]
Yeah, haven't had enough time to finish mockups, hope will finish them by next week.

**Comment by brylie** [comment]
This issue was moved to Crowducate/crowducate-platform#44
