### ISSUE TITLE
Create Turi logo and outlook

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#101]
Create brand resources for Turi, including:
- [ ] Logo
- [ ] Color
- [ ] Typography
- [ ] Slogan

**Comment by JuusoV** [comment]
Inspiration for slogans: http://www.hongkiat.com/blog/77-catchy-and-creative-slogans/

**Comment by brylie** [comment]
This issue was moved to Crowducate/crowducate-platform#52
