### ISSUE TITLE
Create user profile wireframes

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#105]
Users want to manage their profile fields, e.g. change email. Make it possible for users to manage their own name, email, and other details.
- [ ] Start wireframes

**Comment by Rahbaran** [comment]
@sbe: First version. I think is feasible. Please have a look at the crowducate.me and the old source code for inspiration.

![editing settings](https://cloud.githubusercontent.com/assets/3035315/7333419/a4776e34-eb6f-11e4-875d-b8ed63931342.png)

**Comment by brylie** [comment]
Josh Owens wrote a relevant [article about user profile security](http://joshowens.me/the-curious-case-of-the-unknowing-leaky-meteor-security/). Basically, we need to be careful what we allow users to enter into their profile fields, which affects how we implement this profile feature.
