### ISSUE TITLE
Review existing Finnish and Russian translations

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#107]
Work with Taija to review existing Finnish translations.

**Comment by bajiat** [comment]
Finnish translations have been reviewed togethew with Vesa and partially modified/corrected. Still considering the wording in Finnish for "Cover photo" and "Courses tagged".
Russian translations will be reviewed once Vesa finds a convenient way for me to review them.
We also discussed that it would be good if the translation tool was able to show translation for multiple languages in one view. This could be beneficial e.g. for reviewing crowdsourced translations (style). Vesa planned comment this for the tool developers.

**Comment by JuusoV** [comment]
I believe the best word for "Cover photo" in finnish would be simply "Kansikuva" atleast that is what Facebook uses.

**Comment by bajiat** [comment]
"Kansikuva" is what we used as the translation.
