### ISSUE TITLE
Audit Serendipity OER search engine

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#110]
Take a look at the [Serendipity OER search engine](http://serendipity.utpl.edu.ec/). Make notes about your thoughts and experience on the [Open Educational Resource landscape audit](https://crowducate.hackpad.com/Open-Education-audit-97TwvJ5ARPs#:h=Serendipity) document.

**Comment by bajiat** [comment]
Notes on Serendipity available in the audit document.
