### ISSUE TITLE
Subject/category/topic metadata input

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#12]
Provide a field for course creators to select from pre-determined course categories. E.g. Biology, Chemistry, Physics, etc..
- [x] Read through the [course subjects and topics document](https://crowducate.hackpad.com/Course-subjects-or-topics-Z3E7jEYxu1E)
- [x] Determine user interface options for selecting multiple categories for a course
- [x] Design one or more wireframes depicting the widget option(s)
## User stories

As a teacher
I need to categorize my courses, using a common vocabulary
so that my course can be used in relevant contexts, courses, etc

As a teacher
I need courses to be categorized with common topics
so that I can find resources relevant to my course

**Comment by JuusoV** [comment]
An idea how to implement this can be found on the hackpad discussion linked above. Please make sure to read my comment under the wireframe.
