### ISSUE TITLE
Create user personas

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#128]
Create two or more user personas describing idealized Crowwducate users. These personas can come from existing known users, with private details changed.

These personas will be used to guide the development process.
- [ ] Brainstorm
- [ ] Document
## User stories

As a designer
I would like to know more about who I am designing for
so I can make design decisions in their interest

As a developer
I would like to know more about the users of the application
so that I can build a platform that is genuinely useful

As a business owner
I would like to know about my users
so that I can plan features and services to meet their needs

**Comment by bajiat** [comment]
We organised a brainstorming session on the personas on 13th April and created two personas: Paula and Maria (both teachers). You can find them documented in Hackpad:
https://crowducate.hackpad.com/Paula-Persona-e39Tv5N0Mia
https://crowducate.hackpad.com/Maria-Persona-RVWCCxKgdeF

A couple of things still missing from the Paula persona.
