### ISSUE TITLE
Create list of subjects or topics for courses

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#129]
Create a list of course categories. E.g. Biology, Chemistry, Physics...
## Deliverable

List of 5-20 topics.
## Resources
- Khan Academy
- Finnish education 
## User stories

As a teacher

I need to categorize my courses, using a common vocabulary

so that my course can be used in relevant contexts, courses, etc

As a teacher

I need courses to be categorized with common topics

so that I can find resources relevant to my course

**Comment by bajiat** [comment]
First draft for a list of subjects can be found from: https://crowducate.hackpad.com/Course-subjects-or-topics-Z3E7jEYxu1E

**Comment by brylie** [comment]
Really great work Taija! :-)

**Comment by bajiat** [comment]
Final suggestion now available in https://crowducate.hackpad.com/Course-subjects-or-topics-Z3E7jEYxu1E. There are some items in the list I'm uncertain about (in italics). Please comment the proposal.

**Comment by brylie** [comment]
@bajiat you rock!
