### ISSUE TITLE
Research Tekes as possible funding source

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#130]
The following details will be helpful to find when researching potential funding sources.
- Website
- Mission Statement
- Types of projects funded
- Examples of previous projects funded
  *Amount of funding available
- Funding limit for individual applicants
- Link to application instructions (or similar document)
- Application deadline or other important dates

**Comment by Laura-Sampo** [comment]
http://www.tekes.eu/horisontti-2020/perusteet/

**Comment by brylie** [comment]
This issue was moved to Crowducate/crowducate-platform#55
