### ISSUE TITLE
Create i18n guidelines document

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#133]

**Comment by bajiat** [comment]
The i18n guidelines document can be found from https://crowducate.hackpad.com/i18n-guidelines-for-Crowducate-7hdx36zPaAQ

Feel free to comment. I'm especially grateful for comments regarding the examples - if they don't for example apply to the technologies used in Crowducate.  Also, let me know if you would like some section to be further illustrated. There are also two open issues in the document.

**Comment by bajiat** [comment]
The i18n guidelines document can be found from https://crowducate.hackpad.com/i18n-guidelines-for-Crowducate-7hdx36zPaAQ

Feel free to comment. I'm especially grateful for comments regarding the examples - if they don't for example apply to the technologies used in Crowducate.  Also, let me know if you would like some section to be further illustrated. There are also two open issues in the document.
