### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Rahbaran** [meteorcrowd/crowducate-next#137]

**Comment by brylie** [comment]
Just in case this is helpful, basic instructions for translation.

## Set up MessageFormat

Follow the [extracting translation strings](https://github.com/gadicc/meteor-messageformat#extracting-translation-strings) instructions.

## Create a development branch
- [Create a new branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/), based on development branch 
  - e.g. _d/german-translation_ would follow our naming convention.
- Pull the most recent changes from Github
- Checkout the translation branch _d/german-translation_ locally

## Access the translation screen
- Launch meteor
- Navigate to **localhost:3000/translate**
- Create the german language using two letter ISO language code
