### ISSUE TITLE
Merge the repos part I

### ISSUE THREAD

**Issue by Rahbaran** [meteorcrowd/crowducate-next#139]
There are two main steps to merge the repos. More details here: https://crowducate.hackpad.com/Merging-the-two-repos-mvr1gHyMGF1

**Comment by Rahbaran** [comment]
@brylie: Do you think you can do part 1 (i.e., the merge "proper")? I assume your git/github skills are much much better than mine ;)

**Comment by brylie** [comment]
Yes, I would like to consider code provenance a bit, after some 
reflection. Would you consider with me the possibility of donating the 
code to, and working on it under, a non-profit organization such as the 
Open Knowledge Foundation? It would still have the same freedoms, but 
might save us some politics.

In service,
Brylie Christopher Oxley

**Comment by brylie** [comment]
E.g. we can become part of the [Open Knowledge Network](https://okfn.org/get-involved/network-projects/).

**Comment by brylie** [comment]
The main reason I suggest OKFN, is they have an [Open Education Working Group](http://education.okfn.org/).

**Comment by brylie** [comment]
This issue was moved to Crowducate/crowducate-platform#43

**Comment by brylie** [comment]
This issue was moved to Crowducate/crowducate-platform#57
