### ISSUE TITLE
Create Business Model Canvas

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#147]

**Comment by Rahbaran** [comment]
I have a two canvasses here, created during two different startup weekends.

**Comment by brylie** [comment]
Great :-) May we add them to Hackpad?

**Comment by Rahbaran** [comment]
will do, I can't find them right now (not digitalized, yet). but i'm going to have a more thorough look tomorrow late evening.

**Comment by Rahbaran** [comment]
not successful, yet. give me one more day.

**Comment by Rahbaran** [comment]
I found our first bmc (developed at startup weekend berlin, end of 2013). Obviously, this was just an initial idea. 

![businessmodel_canvas_crowducate](https://cloud.githubusercontent.com/assets/3035315/7285427/b443667e-e944-11e4-815d-2e1f4945f80a.jpg)

It might make more sense to use the lean canvas (a slight modification) which I also have here. We can discuss this in the next hangout.

**Comment by brylie** [comment]
This issue was moved to Crowducate/crowducate-platform#96
