### ISSUE TITLE
Add UI translations platform (i18n)

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#18]
Add internationalization (i18n) framework to Crowducate platform.
## User story

As an end user
I would like the Crowducate interface to display text in my native language
so that I understand the user interface text to navigate the platform
## Available option(s)
- [tap:i18n](https://github.com/TAPevents/tap-i18n)
- [gadicc:meteor-messageformat](https://github.com/gadicc/meteor-messageformat)

**Comment by brylie** [comment]
[Related issue](https://github.com/Crowducate/crowducate.me/issues/36) in Crowducate.me.

**Comment by dcsan** [comment]
i used a different package because i needed two languages to be supported at once, which tap didn't handle.

**Comment by Rahbaran** [comment]
@dcsan: which package do you use? are you happy with it?

**Comment by dcsan** [comment]
i used one of gadi cohen's packages. another benefit was that it has a crowdsourced translation UI built in. however not sure how well its supported/developed, he is spread really thin.  i did a pros/cons writeup on the google group i believe tho maybe tap project has evolved since then,

**Comment by dcsan** [comment]
i'm doing an app for ppl to learn languages, hence having the UI in one lang and content in another was important. that may not be a concern for you

**Comment by brylie** [comment]
I have found [gadicc:messageformat.js](https://github.com/gadicc/messageformat.js) and [gadicc:meteor-messageformat](https://github.com/gadicc/meteor-messageformat), but may be missing another package.

@dcsan will you please provide us with a link to the specific package you use?

**Comment by brylie** [comment]
@dcsan will you please provide us with a link to your writeup?

**Comment by dcsan** [comment]
https://groups.google.com/forum/#!searchin/meteor-talk/message-format/meteor-talk/e6I4yfMgV_c/Drwu7qJyI6IJ

christoph -

these are all good points. did you get to any conclusions on which libs are best on these parameters?
I really like the crowdsourced translation tool that's already there with message format.

another issue for me is that the original language is also being edited while the translation is happening. however I don't want to use lookup keys for everything. messageFormat seems to support some type of fuzzy matching and also revision tracking (at least going by the docs, haven't tried it yet)

/dc
- hide quoted text -
  On Wed, Sep 24, 2014 at 4:03 AM, Christoph Richter christoph@zoomsquare.com wrote:
- hide quoted text -
  We are also in the Process in selecting a tool (but in the beginning)

other reasons that come in mind:
- How easy you can add an external translation network. a second and third language is easy. but when you go for 10+ languages you want to have a external service translating it.
- how good the technology supports reuse of translations - so you do not have 10 times the "ok" text there. as it then can lead to weird results
- if it supports a preview or inline editing that the editor sees the translation in context
- conextual tips with translation in general (a description text for the translator)
- language packs . that some of the translations can be used in other projects as well (e.g. a shared lib between web and app)

Am Montag, 22. September 2014 22:16:46 UTC+2 schrieb David Collier:
It seems there are two big projects for translation. I'm trying to evaluate which one to use so would appreciate any feedback from others who made this decision. My notes / two main projects are below.

# MessageFormat

http://messageformat.meteor.com/

PROS
- based on MessageFormat.js substantial lib
- includes extraction tool 
- handles fuzzy strings and versions, if strings are updated in the app
- javascript and handlebars methods
- prebuilt translation tool / webUI for string translations
  http://messageformat.meteor.com/translate/af
- written by Gadi, meteor guru active community guy

# TAP i18n

https://github.com/TAPevents/

notes:
- based on i18next engine
- uses AJAX to load languages

PROS
- helpers for bootstrap/language pickers
- support for packages
- support for DB collection translation
  https://github.com/TAPevents/tap-i18n-db)

CONS?
- only JSON format, no yaml, so tedious to edit
- no webUI for managing strings

There are some other projects such as https://github.com/Nemo64/meteor-translator
but the two above seem the most thorough.  Have I missed any others?

What other criteria have people use when selecting the right tool? The underlying tech of messageFormat vs. i18next seems a factor.

# Questions:

1) Multiple languages in page
I'm trying to do a bilingual app but:

> Tap: "Only the required translations for the current client's language are sent over the wire"
> does this mean the language can only be A or B, but not a mixture, switched automagically based on a session?
> ie how to provide helpers in a page to have multiple translation
>   EN: {{tr "string", 'en'}}
>   FR: {{tr "string", 'fr'}}

2) Capturing data
At least messageFormat project will capture/extract strings in static pages, but if I have a lot of content already in complex mongo collections, is there a way to capture this? 

Thanks for any insight from the package creators or others in this area.

/dc

**Comment by brylie** [comment]
We are also leaning towards MessageFormat. Please add any relevant details to our [i18n research document](https://crowducate.hackpad.com/i18n-platform-comparison-PBc8mpFBmZ8).

**Comment by brylie** [comment]
I am having a bit of trouble getting Meteor-MessageFormat to work. I have opened, or contributed to, the following issues:
- [mf_extract doesn't work](https://github.com/gadicc/meteor-messageformat/issues/77)
- [meteor add gadicc:messageformat: no such package](https://github.com/gadicc/meteor-messageformat/issues/98)
