### ISSUE TITLE
Compare i18n platforms and choose one

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#71]
Identify primary options for i18n solution, compare, contrast, and choose one.
## User Story

As a developer
I would like to begin inserting translation strings into the Crowducate UI
so that translation work may commence

As a project manager
I would like to know the pros and cons of i18n options
so that our team can make an informed decision on a solution
## Deliverables
- [x] [Comparison document](https://crowducate.hackpad.com/i18n-platform-comparison-PBc8mpFBmZ8)
- [x] Implementation plan

**Comment by brylie** [comment]
Parent task: #18

**Comment by brylie** [comment]
Based on feedback from Vesa and dcsan, I am leaning towards the MessageFormat.js library.

**Comment by dcsan** [comment]
which did you choose in the end?

**Comment by brylie** [comment]
We chose MessageFormat. We have been adding the _mf_ helper to all template strings, and have had 100% translation for Finnish and Russian languages. Yesterday, I changed some of the _mf_ translation keys, for consistency, which may have broken some of the existing translations.

**Comment by dcsan** [comment]
i thought you had some tech issues with MF? what were they and you got around them ok?

in terms of managing "crowdsourcing" of translating content
are you using the MF screens, or some external service and just dropping the content into the app?

**Comment by brylie** [comment]
The troubles I encountered turned out to be mainly an issue of lacking documentation. We have updated the documentation on the mf readme, and the mf docs site will be updated soon.

MF screens so far, since translation efforts have been in-house.
