### ISSUE TITLE
Add course creation date on insert

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#87]
Add a [dateCreated](http://schema.org/dateCreated) to each course when it is inserted into the collection. 

This can be done via a [collection hook](https://github.com/matb33/meteor-collection-hooks) as described in the article [Meteor Methods vs. Client Side Operations](https://www.discovermeteor.com/blog/meteor-methods-client-side-operations/)
## User Stories

```
As a learner
I want to know when a course was created
so I can determine its recency
```

```
As a developer
I need course documents to contain a createdAt date
so that I can build a sort feature
```

**Comment by JuusoV** [comment]
Material I used to study about collections:
http://docs.meteor.com/#/basic/
https://www.meteor.com/try/3

**Comment by brylie** [comment]
Great, thanks! Will you please introduce Vesa to the idea, perhaps the Todo app? 

On 23 March 2015 14:07:07 EET, Juuso Vallius notifications@github.com wrote:

> Material I used to study about collections:
> http://docs.meteor.com/#/basic/
> https://www.meteor.com/try/3
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Crowducate/crowducate-next/issues/87#issuecomment-84965898

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Rahbaran** [comment]
This is also great. http://meteortips.com/book/databases-part-1/ The whole book is great (and the blog has some beginner friendly tuts on the iron router).
