### ISSUE TITLE
Refactor 'add' buttons to use single template

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/crowducate-next#90]
There are several 'add' buttons on the course page, including 'add section', 'add lesson'. See if these buttons can be refactored to use one template, and adjust the parent template events to target the new button element. 

This will simplify the translation process and possibly make the codebase easier to maintain.
## User Stories

```
As a translator
I would like to only translate a string once
so I can reduce duplication of effort and possible errors
```

```
As a developer
I would like to reuse components often
to reduce my codebase and make maintenance easier.
```

**Comment by sebbel** [comment]
Running into problems with the parentData of the lesson event.

**Comment by brylie** [comment]
We may need to refactor the course structure so that course sections are stored in their own collection. This would make it so that the parentData is no longer necessary.

**Comment by brylie** [comment]
The package [Blaze Components](http://components.meteor.com/) may come in handy for tasks like this.

**Comment by brylie** [comment]
This issue was moved to Crowducate/crowducate-platform#92
